//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.13 at 08:23:55 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.xpadro.spring.samples.com/employees", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.samples.spring.xpadro.employees;
